name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Run Tests
        run: uv run pytest
      - name: Run Flake8
        run: uv run flake8 src tests
      - name: Run Black
        run: uv run black src tests
      - name: MyPy
        run: uv run mypy src


